name: Flutter Web Docker CI/CD

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Đăng nhập vào Docker Hub sử dụng Token bảo mật đã cấu hình
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Thiết lập Buildx môi trường build của Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Tiến hành build và push image lên Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # LƯU Ý: Nếu thư mục chứa Flutter của bạn tên là 'mobile', hãy đổi '.' thành './mobile'
          # Nếu file Dockerfile nằm ngay thư mục ngoài cùng thì giữ nguyên '.'
          context: ./mobile
          file: ./mobile/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flutter-horse-app:latest
